'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18444
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Proxy() As String
            Get
                Return CType(Me("Proxy"),String)
            End Get
            Set
                Me("Proxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property loginproxy() As String
            Get
                Return CType(Me("loginproxy"),String)
            End Get
            Set
                Me("loginproxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property passproxy() As String
            Get
                Return CType(Me("passproxy"),String)
            End Get
            Set
                Me("passproxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Purgefichiers() As Integer
            Get
                Return CType(Me("Purgefichiers"),Integer)
            End Get
            Set
                Me("Purgefichiers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AutoUpdate() As Integer
            Get
                Return CType(Me("AutoUpdate"),Integer)
            End Get
            Set
                Me("AutoUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property intervalmiseajour() As Integer
            Get
                Return CType(Me("intervalmiseajour"),Integer)
            End Get
            Set
                Me("intervalmiseajour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property datemajmiseajour() As String
            Get
                Return CType(Me("datemajmiseajour"),String)
            End Get
            Set
                Me("datemajmiseajour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FadeOut() As Integer
            Get
                Return CType(Me("FadeOut"),Integer)
            End Get
            Set
                Me("FadeOut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProxyPort() As String
            Get
                Return CType(Me("ProxyPort"),String)
            End Get
            Set
                Me("ProxyPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property WindowSizeMain() As Global.System.Drawing.Size
            Get
                Return CType(Me("WindowSizeMain"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WindowSizeMain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property WindowLocationMain() As Global.System.Drawing.Point
            Get
                Return CType(Me("WindowLocationMain"),Global.System.Drawing.Point)
            End Get
            Set
                Me("WindowLocationMain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WindowState() As SByte
            Get
                Return CType(Me("WindowState"),SByte)
            End Get
            Set
                Me("WindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Slide() As SByte
            Get
                Return CType(Me("Slide"),SByte)
            End Get
            Set
                Me("Slide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl)>  _
        Public Property Lienmiseajour() As String
            Get
                Return CType(Me("Lienmiseajour"),String)
            End Get
            Set
                Me("Lienmiseajour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastChanged() As Date
            Get
                Return CType(Me("LastChanged"),Date)
            End Get
            Set
                Me("LastChanged") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bIntegrPerim() As Boolean
            Get
                Return CType(Me("bIntegrPerim"),Boolean)
            End Get
            Set
                Me("bIntegrPerim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property tracelog() As Boolean
            Get
                Return CType(Me("tracelog"),Boolean)
            End Get
            Set
                Me("tracelog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MMTVSource() As String
            Get
                Return CType(Me("MMTVSource"),String)
            End Get
            Set
                Me("MMTVSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property dureecesoir() As SByte
            Get
                Return CType(Me("dureecesoir"),SByte)
            End Get
            Set
                Me("dureecesoir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firststart() As Boolean
            Get
                Return CType(Me("firststart"),Boolean)
            End Get
            Set
                Me("firststart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Autoverif() As SByte
            Get
                Return CType(Me("Autoverif"),SByte)
            End Get
            Set
                Me("Autoverif") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property datemajverif() As String
            Get
                Return CType(Me("datemajverif"),String)
            End Get
            Set
                Me("datemajverif") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property intervalverif() As SByte
            Get
                Return CType(Me("intervalverif"),SByte)
            End Get
            Set
                Me("intervalverif") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property dureemaintenant() As SByte
            Get
                Return CType(Me("dureemaintenant"),SByte)
            End Get
            Set
                Me("dureemaintenant") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Cacher_Filtre() As Boolean
            Get
                Return CType(Me("Cacher_Filtre"),Boolean)
            End Get
            Set
                Me("Cacher_Filtre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property buttonsstate() As Integer
            Get
                Return CType(Me("buttonsstate"),Integer)
            End Get
            Set
                Me("buttonsstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property buttonssave() As SByte
            Get
                Return CType(Me("buttonssave"),SByte)
            End Get
            Set
                Me("buttonssave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Cheminmiseajour() As String
            Get
                Return CType(Me("Cheminmiseajour"),String)
            End Get
            Set
                Me("Cheminmiseajour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property URLChecked() As Boolean
            Get
                Return CType(Me("URLChecked"),Boolean)
            End Get
            Set
                Me("URLChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIRChecked() As Boolean
            Get
                Return CType(Me("DIRChecked"),Boolean)
            End Get
            Set
                Me("DIRChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property noupdate() As Boolean
            Get
                Return CType(Me("noupdate"),Boolean)
            End Get
            Set
                Me("noupdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CallUpgrade() As Boolean
            Get
                Return CType(Me("CallUpgrade"),Boolean)
            End Get
            Set
                Me("CallUpgrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property dualmonitor() As Integer
            Get
                Return CType(Me("dualmonitor"),Integer)
            End Get
            Set
                Me("dualmonitor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ConfHardware() As Integer
            Get
                Return CType(Me("ConfHardware"),Integer)
            End Get
            Set
                Me("ConfHardware") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property boutonbas1() As Integer
            Get
                Return CType(Me("boutonbas1"),Integer)
            End Get
            Set
                Me("boutonbas1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property nbchainesdiff() As Integer
            Get
                Return CType(Me("nbchainesdiff"),Integer)
            End Get
            Set
                Me("nbchainesdiff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property scrollhorizontal() As Boolean
            Get
                Return CType(Me("scrollhorizontal"),Boolean)
            End Get
            Set
                Me("scrollhorizontal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property accordscrollhorizontal() As Boolean
            Get
                Return CType(Me("accordscrollhorizontal"),Boolean)
            End Get
            Set
                Me("accordscrollhorizontal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property oldUI() As Integer
            Get
                Return CType(Me("oldUI"),Integer)
            End Get
            Set
                Me("oldUI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FichierCorrompu() As Integer
            Get
                Return CType(Me("FichierCorrompu"),Integer)
            End Get
            Set
                Me("FichierCorrompu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property UserRestart() As Integer
            Get
                Return CType(Me("UserRestart"),Integer)
            End Get
            Set
                Me("UserRestart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BddExists() As Boolean
            Get
                Return CType(Me("BddExists"),Boolean)
            End Get
            Set
                Me("BddExists") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UrlUpdate() As Boolean
            Get
                Return CType(Me("UrlUpdate"),Boolean)
            End Get
            Set
                Me("UrlUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ManualFeedBack() As Boolean
            Get
                Return CType(Me("ManualFeedBack"),Boolean)
            End Get
            Set
                Me("ManualFeedBack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("117")>  _
        Public Property memortbheight() As Integer
            Get
                Return CType(Me("memortbheight"),Integer)
            End Get
            Set
                Me("memortbheight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property decalage_horaire() As Integer
            Get
                Return CType(Me("decalage_horaire"),Integer)
            End Get
            Set
                Me("decalage_horaire") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property EngineSelection() As Integer
            Get
                Return CType(Me("EngineSelection"),Integer)
            End Get
            Set
                Me("EngineSelection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EngineShow() As Boolean
            Get
                Return CType(Me("EngineShow"),Boolean)
            End Get
            Set
                Me("EngineShow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RssFeed() As String
            Get
                Return CType(Me("RssFeed"),String)
            End Get
            Set
                Me("RssFeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RssFeedMinute() As Boolean
            Get
                Return CType(Me("RssFeedMinute"),Boolean)
            End Get
            Set
                Me("RssFeedMinute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RssFeedLanguage() As Boolean
            Get
                Return CType(Me("RssFeedLanguage"),Boolean)
            End Get
            Set
                Me("RssFeedLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DataBaseExpired() As Boolean
            Get
                Return CType(Me("DataBaseExpired"),Boolean)
            End Get
            Set
                Me("DataBaseExpired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PluginBoot() As Boolean
            Get
                Return CType(Me("PluginBoot"),Boolean)
            End Get
            Set
                Me("PluginBoot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ToolTipsBallon() As Boolean
            Get
                Return CType(Me("ToolTipsBallon"),Boolean)
            End Get
            Set
                Me("ToolTipsBallon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NotifyIconShow() As Boolean
            Get
                Return CType(Me("NotifyIconShow"),Boolean)
            End Get
            Set
                Me("NotifyIconShow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ModifPrefRestart() As Integer
            Get
                Return CType(Me("ModifPrefRestart"),Integer)
            End Get
            Set
                Me("ModifPrefRestart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GestionSave() As Boolean
            Get
                Return CType(Me("GestionSave"),Boolean)
            End Get
            Set
                Me("GestionSave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ResumeChecked() As SByte
            Get
                Return CType(Me("ResumeChecked"),SByte)
            End Get
            Set
                Me("ResumeChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ResumeBefore() As SByte
            Get
                Return CType(Me("ResumeBefore"),SByte)
            End Get
            Set
                Me("ResumeBefore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationTous() As SByte
            Get
                Return CType(Me("RestaurationTous"),SByte)
            End Get
            Set
                Me("RestaurationTous") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationDataBase() As SByte
            Get
                Return CType(Me("RestaurationDataBase"),SByte)
            End Get
            Set
                Me("RestaurationDataBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationChaines() As SByte
            Get
                Return CType(Me("RestaurationChaines"),SByte)
            End Get
            Set
                Me("RestaurationChaines") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationUrl() As SByte
            Get
                Return CType(Me("RestaurationUrl"),SByte)
            End Get
            Set
                Me("RestaurationUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationUserConfig() As SByte
            Get
                Return CType(Me("RestaurationUserConfig"),SByte)
            End Get
            Set
                Me("RestaurationUserConfig") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AudioOn() As Boolean
            Get
                Return CType(Me("AudioOn"),Boolean)
            End Get
            Set
                Me("AudioOn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AudioVolume() As Integer
            Get
                Return CType(Me("AudioVolume"),Integer)
            End Get
            Set
                Me("AudioVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("chimes.wav")>  _
        Public Property RSSSound() As String
            Get
                Return CType(Me("RSSSound"),String)
            End Get
            Set
                Me("RSSSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("notify.wav")>  _
        Public Property MessagesSound() As String
            Get
                Return CType(Me("MessagesSound"),String)
            End Get
            Set
                Me("MessagesSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tada.wav")>  _
        Public Property ReminderSound() As String
            Get
                Return CType(Me("ReminderSound"),String)
            End Get
            Set
                Me("ReminderSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property RSSVolume() As Integer
            Get
                Return CType(Me("RSSVolume"),Integer)
            End Get
            Set
                Me("RSSVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property MessagesVolume() As Integer
            Get
                Return CType(Me("MessagesVolume"),Integer)
            End Get
            Set
                Me("MessagesVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property ReminderVolume() As Integer
            Get
                Return CType(Me("ReminderVolume"),Integer)
            End Get
            Set
                Me("ReminderVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CurrentVersion() As String
            Get
                Return CType(Me("CurrentVersion"),String)
            End Get
            Set
                Me("CurrentVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firstDIRChecked() As Boolean
            Get
                Return CType(Me("firstDIRChecked"),Boolean)
            End Get
            Set
                Me("firstDIRChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firstURLChecked() As Boolean
            Get
                Return CType(Me("firstURLChecked"),Boolean)
            End Get
            Set
                Me("firstURLChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserMail() As String
            Get
                Return CType(Me("UserMail"),String)
            End Get
            Set
                Me("UserMail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property RestaurationLogos() As SByte
            Get
                Return CType(Me("RestaurationLogos"),SByte)
            End Get
            Set
                Me("RestaurationLogos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoRestartManualUpdate() As Boolean
            Get
                Return CType(Me("AutoRestartManualUpdate"),Boolean)
            End Get
            Set
                Me("AutoRestartManualUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Systray() As Boolean
            Get
                Return CType(Me("Systray"),Boolean)
            End Get
            Set
                Me("Systray") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ZGuideTV.My.MySettings
            Get
                Return Global.ZGuideTV.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
