'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.239
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ZGuideTV.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _169() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_169", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AddTableHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddTableHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à d326deefead2f439484cee0a52ac954f385b5c18a6a81f96c53869341e8618c8.
        '''</summary>
        Friend ReadOnly Property API_GEOLOCATION() As String
            Get
                Return ResourceManager.GetString("API_GEOLOCATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à BFEDF296629DB021.
        '''</summary>
        Friend ReadOnly Property API_KEY() As String
            Get
                Return ResourceManager.GetString("API_KEY", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asterisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asterisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asteriskrouge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asteriskrouge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property audiominus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audiominus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property audioplus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audioplus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bell() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bell", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bg_Aero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bg_Aero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bleu_tv_ericdesign1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bleu_tv_ericdesign1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bleu_tv_ericdesign2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bleu_tv_ericdesign2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calendar_scheduleHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar_scheduleHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chance_of_rain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chance_of_rain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chance_of_snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chance_of_snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chance_of_storm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chance_of_storm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chance_of_tstorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chance_of_tstorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cloudy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloudy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property controlplay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("controlplay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_NewRecordHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DataContainer_NewRecordHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_NewRecordHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property datalink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("datalink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property decalage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("decalage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dolby() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dolby", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvdbox_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvdbox_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvdbox_front1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvdbox_front1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property episode_notfound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("episode_notfound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoile_grise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoile_grise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoile_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoile_jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoile_rouge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoile_rouge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoile1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoile1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property etoilesmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etoilesmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filters() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filters", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filters1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filters1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FindHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property findLocation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("findLocation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flurries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flurries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property haze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("haze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HideDescription() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HideDescription", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_bleu_tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_bleu_tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ktv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ktv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loader4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_bleu_tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_bleu_tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_bleu_tv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_bleu_tv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_bleu_tv11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_bleu_tv11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miseajour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miseajour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miseajour1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miseajour1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miseajour21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miseajour21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miseajour22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miseajour22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mmtv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mmtv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mostly_cloudy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mostly_cloudy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mostly_sunny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mostly_sunny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetworkConfiguration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetworkConfiguration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewReportHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewReportHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewReportHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewReportHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property partly_cloudy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("partly_cloudy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PauseRecorderHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseRecorderHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pave4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pave4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paypaldonate1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paypaldonate1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property premiere() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premiere", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printeradd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printeradd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progressbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PropertiesHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PropertiesHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PublishPlanHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PublishPlanHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property season_notfound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("season_notfound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property security() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("security", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SendBackwardHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendBackwardHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property separator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("separator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property signaletique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signaletique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property signaletique1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signaletique1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sleet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sleet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smoke() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smoke", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property soundmute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soundmute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splash_bleu_tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash_bleu_tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splash3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star1cz8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star1cz8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star2nn9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star2nn9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star2nn91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star2nn91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stargho3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stargho3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stars_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stars_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property starynz0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starynz0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stereo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stereo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property storm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("storm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sunny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sunny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teletext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teletext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thunderstorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thunderstorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvdb_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvdb_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvdb_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvdb_logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property world_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("world_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ziplogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ziplogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
